name: Deploy Nginx
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Build and push Docker image
        env: |
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker build -t europe-west3-docker.pkg.dev/$GCP_PROJECT/first-application/nginx:latest .
          docker push europe-west3-docker.pkg.dev/$GCP_PROJECT/first-application/nginx:latest
